import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f9fb",
  },
  scrollView: {
    flex: 1,
    backgroundColor: "#f8f9fb",
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 16,
    gap: 16,
  },
  heroCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 16,
    boxShadow: "0px 2px 8px rgba(0, 0, 0, 0.06)",
  },
  petEmoji: {
    fontSize: 44,
  },
  petName: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1a1a2e",
    marginTop: 8,
  },
  petMeta: {
    fontSize: 14,
    color: "#666",
    marginTop: 4,
  },
  petBrief: {
    fontSize: 14,
    color: "#555",
    marginTop: 10,
    lineHeight: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1a1a2e",
  },
  symptomRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 11,
    marginTop: 10,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: "#9aa0ad",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  checkboxChecked: {
    backgroundColor: "#4e6ef2",
    borderColor: "#4e6ef2",
  },
  checkMark: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "700",
  },
  symptomLabel: {
    fontSize: 14,
    color: "#202638",
    flex: 1,
  },
  uploadPlaceholderBox: {
    width: "100%",
    height: 170,
    borderRadius: 12,
    marginTop: 10,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: "#9aa0ad",
    backgroundColor: "#f3f5fa",
    alignItems: "center",
    justifyContent: "center",
  },
  uploadPlaceholderText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#4b5568",
  },
  symptomTagInputRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    gap: 10,
  },
  symptomTagInput: {
    flex: 1,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#d3d9e6",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#1a1a2e",
    fontSize: 14,
  },
  addTagButton: {
    backgroundColor: "#4e6ef2",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  addTagButtonText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 14,
  },
  symptomTagList: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  symptomTagChip: {
    backgroundColor: "#e5ecff",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  symptomTagChipText: {
    color: "#2440b8",
    fontSize: 13,
    fontWeight: "600",
  },
  diagnoseButton: {
    marginTop: 12,
    backgroundColor: "#1f6f5f",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
  },
  diagnoseButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700",
  },
  footerSpacer: {
    height: 170,
  },
  stickyEmergencyFooter: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 12,
    borderTopWidth: 1,
    borderTopColor: "#dce1ec",
    backgroundColor: "#f8f9fb",
  },
  emergencyButton: {
    marginTop: 6,
    backgroundColor: "#d94848",
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
  },
  emergencyButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  emergencyHint: {
    color: "#666",
    fontSize: 12,
    marginTop: 8,
  },
});
